services:
  web:
    build: .
    container_name: epaper_server
    ports:
      - "4200:4200"
    volumes:
      - ./bitmaps:/app/bitmaps
      - ./data:/app/data
      - ./static:/app/static
    environment:
      - ADMIN_PASSWORD=z0000l
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BASE_URL=https://epaper42.nopshop.com
    restart: always

volumes:
  bitmaps:
  data:
