services:
  web:
    build: .
    container_name: epaper_server
    ports:
      - "4200:4200"
    volumes:
      - ./bitmaps:/app/bitmaps
      - ./data:/app/data
    environment:
      - ADMIN_PASSWORD=z0000l
    restart: always

volumes:
  bitmaps:
  data:
